import './style.css';
import {questions,fields,emptyState,validateState,PracticeTimer} from './core.js';
import {demoStories} from './demo.js';
const $=id=>document.getElementById(id), KEY='rehearsal-mirror-v1';
let state=emptyState(),persisted=true;
try{const saved=localStorage.getItem(KEY);if(saved)state=validateState(JSON.parse(saved));}catch{persisted=false;}
let model='manual',worker,requestId=0,busy=false,pendingRequestId=null;
const timer=new PracticeTimer(state.duration);
document.querySelector('#app').innerHTML=`
<header><a href="#main" class="brand">Rehearsal Mirror<span>PRIVATE INTERVIEW PRACTICE</span></a><a href="#privacy">Your data &amp; privacy</a></header>
<main id="main"><div class="intro"><h1>A little preparation.<br>A clearer answer.</h1><p>Find the right story from your own experience.<br>Practise at your pace, with everything kept in this browser.</p></div>
<div class="workspace"><section class="practice" aria-labelledby="practice-title"><h2 id="practice-title">1. Choose your question</h2><label for="role">Role</label><select id="role"></select><label for="question">Practice question</label><select id="question"></select><p class="question-text" id="question-text"></p>
<div class="timer-row"><div><span class="caption">REHEARSAL TIMER</span><output id="time" aria-label="Seconds remaining">60</output></div><div><label for="duration">Length</label><select id="duration"><option value="60">60 seconds</option><option value="90">90 seconds</option></select><div class="actions"><button id="start">Start</button><button id="restart" class="secondary">Restart</button></div></div></div><p id="timer-status" role="status">Ready when you are.</p>
<label for="answer">Your answer</label><textarea id="answer" maxlength="12000" rows="8" placeholder="Write or rehearse aloud. Keep it true to your experience."></textarea><p class="hint">Try Situation → Task → Action → Result. This tool does not assess your English, employability or hiring prospects.</p></section>
<aside aria-labelledby="retrieval-title"><h2 id="retrieval-title">2. Find a story to draw on</h2><p>The local AI finds related notes in your cards. It does not write experiences for you.</p><button id="load">Download &amp; load local AI</button><progress id="progress" hidden max="100" aria-label="Model file download progress"></progress><p id="model-status" role="status">Manual mode. AI is not loaded. First use needs internet to download the model and runtime (roughly 50 MB).</p><button id="rank" disabled>Find relevant stories</button><p class="hint" id="match-caveat">These are the closest saved cards, not a check that they answer the question. Even the closest card may not fit. Review the full story and use it only if it supports a truthful answer.</p><div id="results" aria-live="polite" aria-busy="false"></div></aside></div>
<section class="stories" aria-labelledby="stories-title"><div class="section-head"><div><h2 id="stories-title">3. Your STAR story cards</h2><p>Use real examples you are comfortable storing on this device.</p></div><div class="actions"><button id="add">Add story</button><button id="demo" class="secondary">Load fictional demo</button></div></div><div id="cards"></div><p id="notice" role="status"></p></section>
<section id="privacy" class="privacy"><h2>Your practice stays with you</h2><p>Answers and stories are saved in this browser’s local storage, never sent to an AI service. Model downloads contact Hugging Face and its file hosts; those hosts see ordinary connection metadata. Use a trusted device. Exported backups contain your text in plain JSON.</p><p>No accounts, paid APIs, tracking or server storage. Internet is needed for the first model download. A loaded model works without further inference requests; a later reload may need internet if browser cache files were cleared. This app does not promise offline startup.</p><div class="actions"><button id="export" class="secondary">Export backup</button><label class="file-button" for="import">Import backup</label><input id="import" type="file" accept=".json,application/json"><button id="delete" class="danger">Delete all practice data</button><button id="cache" class="secondary">Clear downloaded model cache</button></div><p id="storage-status" role="status"></p></section></main><footer>Made for quiet practice. Fictional demo • No generated answers • No hiring scores</footer>`;
function note(text){$('notice').textContent=text;}
function updateMatchingControl(){$('rank').disabled=model!=='ready'||busy||!state.stories.some(s=>[s.title,...fields.map(f=>s[f])].some(t=>t.trim()));}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));persisted=true;}catch{persisted=false;}$('storage-status').textContent=persisted?'Saved on this device only.':'Browser storage unavailable or invalid. Export a backup before closing; changes may not survive reload.';}
function showMatchingHelp(){const p=document.createElement('p');p.className='hint';p.textContent=state.stories.length?'Browse your cards below, or find the closest cards after loading local AI. You can also try fictional examples.':'No story cards yet. Add your own below, or try three clearly labelled fictional examples here.';const demo=document.createElement('button');demo.id='results-demo';demo.className='secondary';demo.textContent='Load fictional demo';demo.onclick=loadDemo;$('results').replaceChildren(p,demo);$('results').setAttribute('aria-busy','false');}
function invalidateResults(){requestId++;showMatchingHelp();updateMatchingControl();}
function save(){persist();invalidateResults();}
function option(select,text,value){const o=document.createElement('option');o.textContent=text;o.value=value;select.append(o);}
for(const role of [...new Set(questions.map(q=>q.role))])option($('role'),role,role);
function showQuestion(){const q=questions[state.question];$('question-text').textContent=q.text;$('answer').value=state.answers[q.id]||'';invalidateResults();}
function showOptions(){ $('question').replaceChildren();for(const q of questions.filter(q=>q.role===$('role').value))option($('question'),q.text,q.id);$('question').value=state.question;showQuestion();}
function drawTimer(){const seconds=timer.tick();$('time').textContent=String(seconds).padStart(2,'0');$('start').textContent=timer.running?'Pause':seconds===0?'Complete':'Start';$('start').disabled=seconds===0;if(seconds===0)$('timer-status').textContent='Practice complete. Take a breath and review your answer.';}
function resetTimer(){timer.reset(state.duration);$('timer-status').textContent='Ready when you are.';drawTimer();}
$('role').value=questions[state.question].role;showOptions();$('duration').value=state.duration;resetTimer();
$('role').onchange=()=>{state.question=questions.find(q=>q.role===$('role').value).id;showOptions();resetTimer();persist();};
$('question').onchange=()=>{state.question=Number($('question').value);showQuestion();resetTimer();persist();};
$('duration').onchange=()=>{state.duration=Number($('duration').value);resetTimer();persist();};
$('answer').oninput=()=>{state.answers[state.question]=$('answer').value;persist();};
$('start').onclick=()=>{timer.running?timer.pause():timer.start();$('timer-status').textContent=timer.running?'Practising. You can pause at any time.':'Paused. Resume when ready.';drawTimer();};$('restart').onclick=resetTimer;setInterval(drawTimer,200);
function drawCards(){
 $('cards').replaceChildren();
 if(!state.stories.length){const p=document.createElement('p');p.className='empty';p.textContent='Your story bank is empty. Add a card, or try the clearly labelled fictional demo.';$('cards').append(p);}
 for(const s of state.stories){const card=document.createElement('article');card.className='story';card.id=`card-${s.id}`;for(const f of ['title',...fields]){const label=document.createElement('label');label.textContent=f==='title'?'Story title':f[0].toUpperCase()+f.slice(1);const input=document.createElement(f==='title'?'input':'textarea');input.maxLength=3000;input.value=s[f];input.rows=3;input.id=`${s.id}-${f}`;label.htmlFor=input.id;input.oninput=()=>{s[f]=input.value;save();};card.append(label,input);}
 const remove=document.createElement('button');remove.className='secondary';remove.textContent='Remove this story';remove.onclick=()=>{if(confirm('Delete this story card? This cannot be undone unless you have a backup.')){state.stories=state.stories.filter(x=>x.id!==s.id);drawCards();save();}};card.append(remove);$('cards').append(card);}
 $('add').disabled=state.stories.length>=40;updateMatchingControl();
}
$('add').onclick=()=>{state.stories.push({id:crypto.randomUUID(),title:'',situation:'',task:'',action:'',result:''});drawCards();save();$('cards').lastElementChild.querySelector('input').focus();};
function loadDemo(){if(state.stories.length&&!confirm('Replace your story cards with three fictional demo cards? Export first if you want to keep them.'))return;state.stories=structuredClone(demoStories);drawCards();save();note('Three fictional cards loaded. These are examples, not your experiences.');}
$('demo').onclick=loadDemo;
$('load').onclick=()=>{model='loading';$('load').disabled=true;$('model-status').textContent='Preparing local runtime and downloading model files…';$('progress').hidden=false;$('progress').removeAttribute('value');worker?.terminate();worker=new Worker(new URL('./embedding.worker.js',import.meta.url),{type:'module'});const activeWorker=worker;
 worker.onmessage=({data})=>{if(worker!==activeWorker)return;if(data.type==='progress'){const p=data.progress;const percent=Number(p.progress);$('model-status').textContent=`${p.status}: ${p.file||'model'}${Number.isFinite(percent)?` · ${Math.floor(percent)}%`:''}`;if(Number.isFinite(percent))$('progress').value=percent;}
 if(data.type==='ready'){model='ready';$('progress').hidden=true;$('model-status').textContent='Local AI ready. Story matching runs in this browser using MiniLM; no text is uploaded.';$('load').textContent='Local AI loaded';updateMatchingControl();}
 if(data.type==='ranked'){if(data.requestId!==pendingRequestId)return;busy=false;pendingRequestId=null;updateMatchingControl();if(data.requestId!==requestId)return;$('results').replaceChildren();$('results').setAttribute('aria-busy','false');data.results.forEach((r,i)=>{const article=document.createElement('article');article.className='match';const h=document.createElement('h3');h.textContent=`${i+1}. ${r.title||'Untitled story'}`;const p=document.createElement('p');p.textContent=`${r.excerpt.field}: ${r.excerpt.text}`;const a=document.createElement('a');a.textContent='Review full card';a.href=`#card-${r.id}`;article.append(h,p,a);$('results').append(article);});}
 if(data.type==='error'){if(data.requestId!==undefined){if(data.requestId!==pendingRequestId)return;busy=false;pendingRequestId=null;updateMatchingControl();if(data.requestId!==requestId)return;}busy=false;invalidateResults();{model='manual';worker?.terminate();worker=null;$('load').disabled=false;$('load').textContent='Retry local AI download';$('progress').hidden=true;}$('model-status').textContent='AI unavailable. Manual mode: choose a card yourself. '+data.message;drawCards();}};
 worker.onerror=()=>{if(worker!==activeWorker)return;worker?.terminate();worker=null;model='manual';busy=false;pendingRequestId=null;invalidateResults();$('load').disabled=false;$('progress').hidden=true;$('model-status').textContent='Local AI could not start. Manual mode: use your cards below. Retry the download or use a current browser.';drawCards();};worker.postMessage({type:'load'});};
$('rank').onclick=()=>{busy=true;pendingRequestId=++requestId;updateMatchingControl();$('results').setAttribute('aria-busy','true');$('results').textContent='Matching your notes locally…';worker.postMessage({type:'rank',requestId:pendingRequestId,question:questions[state.question].text,stories:structuredClone(state.stories.filter(s=>[s.title,...fields.map(f=>s[f])].some(t=>t.trim())))});};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='rehearsal-mirror-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);note('Backup exported. It contains your private practice text; keep it somewhere safe.');};
$('import').onchange=async()=>{try{const file=$('import').files[0];if(!file)return;if(file.size>1000000)throw Error('Backup is too large (maximum 1 MB).');const next=validateState(JSON.parse(await file.text()));if(!confirm('Replace all current practice data with this backup?'))return;state=next;save();$('role').value=questions[state.question].role;showOptions();$('duration').value=state.duration;resetTimer();drawCards();note('Backup restored on this device.');}catch(e){note('Import failed. '+e.message);}finally{$('import').value='';}};
$('delete').onclick=()=>{if(!confirm('Delete ALL story cards and answers from this browser? Existing exported files are not deleted.'))return;state=emptyState();try{localStorage.removeItem(KEY);}catch{}invalidateResults();$('role').value=questions[0].role;showOptions();$('duration').value=60;resetTimer();drawCards();$('storage-status').textContent='All saved practice data removed from this browser. Downloaded model files are separate; use the cache control below.';note('All practice data deleted.');};
$('cache').onclick=async()=>{if(!confirm('Clear cached Transformers model files? The next model load will require a download.'))return;try{worker?.terminate();worker=null;model='manual';busy=false;pendingRequestId=null;invalidateResults();for(const name of await caches.keys())if(name==='transformers-cache')await caches.delete(name);$('model-status').textContent='Model cache cleared. Manual mode. Internet is needed for the next download.';}catch{$('model-status').textContent='Model cache could not be cleared. Local AI is unloaded; manual mode. Retry the download or clear site data through browser settings.';note('Could not clear model cache. Clear this site’s browser data through browser settings.');}finally{$('load').disabled=false;$('load').textContent='Download & load local AI';$('progress').hidden=true;updateMatchingControl();}};
drawCards();$('storage-status').textContent=persisted?'Saved on this device only.':'Browser storage unavailable or invalid. Export before closing.';

